#!/usr/bin/env ruby
# coding: utf-8
require 'ru_propisju'
require 'fest'

charge = `cat /sys/class/power_supply/BAT0/capacity`.to_i
status = `cat /sys/class/power_supply/BAT0/status`.chomp!

procent =
  RuPropisju.propisju_shtuk(charge, 1, ['проце нт', 'проц+ента', 'проц+ентов'])
Fest.new.say(
  if status == 'Discharging' && charge > 10 && charge < 50
    "Заряд батареи #{procent}"
  elsif status == 'Discharging' && charge < 10
    'Критический заряд батареи.'
  end
)
