#!/home/afsmnghr/.rvm/rubies/ruby-2.1-head/bin/ruby
# coding: utf-8
gems = '/home/afsmnghr/.rvm/gems/ruby-2.1-head/gems'
`ls "#{gems}"`.match(/fest-(\d+).(\d+).(\d+)/i)
fest = "fest-#{Regexp.last_match[1]}.#{Regexp.last_match[2]}.#{Regexp.last_match[3]}"
require_relative "#{gems}/#{fest}/lib/fest"

def delete_torrents_done
  @ids = `transmission-remote -l | awk '{ print $1 }`.split("\n")
  @ids -= [@ids[0], @ids[-1]]

  @ids.each do |id|
    system("transmission-remote -t '#{id}' -r")
  end
end

def check_statuses
  @statuses = `transmission-remote -l | awk '{ print $5 }'`.split("\n")
  @statuses -= [@statuses[0], @statuses[-1]]
end

if `export DISPLAY=:0 && xbacklight`.to_i == 0
  check_statuses
  counts = 0

  @statuses.each do |status|
    counts += 1 if status == 'Done'
  end

  sleep 600
  if counts == @statuses.size
    delete_torrents_done
    system('sudo systemctl poweroff')
  end
else
  @fest = Fest.new
  @fest.say('Загр+узка завершена')
end
