#!/usr/bin/env ruby
# coding: utf-8
require 'fest'
require 'active_support'
require 'transmission-rpc'

Transmission.torrents.each do |t|
  t.delete! if t.percent_done.to_i == 1
end

if `cat /sys/class/backlight/intel_backlight/brightness`.to_i == 0
  system('sudo poweroff') if Transmission.torrents.empty?
else
  Fest.new.say('Загр+узка завершена')
end
